include:
  - remote: 'https://gitlab-templates.ddbuild.io/slack-notifier/v1/template.yml'

stages:
  - build

test:
  stage: build
  image: google/cloud-sdk:slim
  tags: ['runner:main', 'size:large']
  before_script:
    - pip install gcloud
    - pip install awscli
    - aws ssm get-parameter --region us-east-1 --name ci.os-manifest.ci-os-manifest.json --with-decryption --query Parameter.Value --out text > ./google-sa.json
    - gcloud auth activate-service-account --key-file ./google-sa.json
  script:
    - echo "gcloud compute instances create gitlab-ci-job-${CI_JOB_ID} --zone us-east1-b --network datadog-build-us-east1 --subnet datadog-build-us-east1-private --tags common,nat-us-east1 --no-address --image-family debian-vmx --machine-type n1-standard-16"
